"""create 7 more tables

Revision ID: 860c983f975b
Revises: ffdc0a98111c
Create Date: 2024-04-24 09:32:07.802278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860c983f975b'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('provider_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        # batch_op.create_unique_constraint(None, ['provider_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        # batch_op.drop_column('provider_name')

    # ### end Alembic commands ###
